-- ============================================================================
-- CIM Work Manager - Oracle Database Initialization Script
-- 适用工具: Aqua Data Studio (批处理分隔符: GO)
-- 数据库版本: Oracle 12c 及以上 (使用 IDENTITY 自增列)
-- 执行方式: 打开本文件 -> 连接目标Oracle实例 -> 整文件"执行"
--
-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║  【量产部署方案 - PANJOB 账号直连】                                    ║
-- ║                                                                        ║
-- ║  · 登录账号: PANJOB (与 EQUIPMENTINFO 同账号，所有新建表落在 PANJOB     ║
-- ║    默认表空间 = EQUIPMENTINFO 所在表空间)                              ║
-- ║  · 机台主表 EQUIPMENTINFO 已存在且为生产数据，本脚本【绝不创建/修改】!  ║
-- ║    后端 ORM 直接映射此真表，前端只读展示。                             ║
-- ║  · 本脚本只创建 13 张业务表 + 1 个类型视图 (EQUIPMENT_TYPES)：         ║
-- ║      PROJECTS / TASKS / EQUIPMENT_TYPES(视图) / CONFIGURATIONS /       ║
-- ║      REQUIREMENTS / CHANGE_RECORDS / REPORTS / NOTES_DOCUMENTS /       ║
-- ║      USERS / SYSTEM_SETTINGS / WORK_CATEGORIES / WORK_ITEMS /         ║
-- ║      DAILY_PLANS / WORK_LOGS                                           ║
-- ║  · 外键 CONFIGURATIONS.EQUIPMENT_NAME / REQUIREMENTS.EQUIPMENT_NAME    ║
-- ║    引用 EQUIPMENTINFO.EQUIPMENT (VARCHAR2 主键)                        ║
-- ║                                                                        ║
-- ║  · 单步部署：本脚本执行完毕即可启动后端，无需第二步!                   ║
-- ║  · 禁止在已有业务数据的环境下重复执行本脚本！DROP 段会清空所有表。     ║
-- ╚════════════════════════════════════════════════════════════════════════╝
--
-- 注意事项:
--   1. 执行前请确认已用 PANJOB 账号登录 (脚本段 0 会自检)
--   2. 所有 CREATE TABLE 不指定 TABLESPACE，自动落在 PANJOB 默认表空间
--   3. 若为 Oracle 11g，请将所有 "GENERATED AS IDENTITY" 改为 SEQUENCE + TRIGGER 方案
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. 执行环境自检
-- ----------------------------------------------------------------------------
-- 显示当前登录用户与实例 (ADS结果面板可见)
SELECT USER         AS CUR_USER,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') AS INST_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME')  AS SVC_NAME
  FROM DUAL
GO
PRINT '===================================================='
PRINT ' 若上面 CUR_USER 不是 PANJOB，请中止并切换连接！     '
PRINT '===================================================='
GO

-- 确认 EQUIPMENTINFO 表存在于当前用户下
SELECT COUNT(*) AS EQUIPMENTINFO_ROWS FROM EQUIPMENTINFO
GO
PRINT '===================================================='
PRINT ' 若上面 EQUIPMENTINFO_ROWS = 0 或报 ORA-00942,         '
PRINT ' 请中止: 当前账号无 EQUIPMENTINFO 表，无法部署!       '
PRINT '===================================================='
GO

-- ----------------------------------------------------------------------------
-- 1. DROP TABLES / VIEWS (级联删除，按外键依赖顺序 — 仅首次部署安全执行)
-- ----------------------------------------------------------------------------
-- 使用 PL/SQL 动态 DROP：对象不存在时不报错，避免首次执行被 ORA-00942 中断
-- ⚠️ 严禁 DROP EQUIPMENTINFO！以下列表中绝无 'EQUIPMENTINFO'
DECLARE
  PROCEDURE drop_if_exists(p_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_name || ' CASCADE CONSTRAINTS PURGE';
    DBMS_OUTPUT.PUT_LINE('DROP TABLE OK : ' || p_name);
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -942 THEN NULL;  -- 表不存在，忽略
    ELSE RAISE; END IF;
  END;
  PROCEDURE drop_view_if_exists(p_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW ' || p_name;
    DBMS_OUTPUT.PUT_LINE('DROP VIEW  OK : ' || p_name);
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -942 THEN NULL;
    ELSE RAISE; END IF;
  END;
BEGIN
  drop_if_exists('WORK_LOGS');
  drop_if_exists('DAILY_PLANS');
  drop_if_exists('WORK_ITEMS');
  drop_if_exists('WORK_CATEGORIES');
  drop_if_exists('SYSTEM_SETTINGS');
  drop_if_exists('USERS');
  drop_if_exists('NOTES_DOCUMENTS');
  drop_if_exists('REPORTS');
  drop_if_exists('CHANGE_RECORDS');
  drop_if_exists('CONFIGURATIONS');
  drop_if_exists('REQUIREMENTS');
  drop_view_if_exists('EQUIPMENT_TYPES');   -- 视图，先于 EQUIPMENT_TYPES 表
  drop_if_exists('TASKS');
  drop_if_exists('PROJECTS');
  COMMIT;
END;
GO

-- ----------------------------------------------------------------------------
-- 2. CREATE TABLES — 13 张业务表全部创建在 PANJOB 下 (与 EQUIPMENTINFO 同表空间)
--    不指定 TABLESPACE，使用 PANJOB 默认表空间。
-- ----------------------------------------------------------------------------

-- 2.1 PROJECTS - 项目表
CREATE TABLE PROJECTS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME            VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION     CLOB,
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'active',
    START_DATE      DATE,
    END_DATE        DATE,
    PROGRESS        NUMBER(10,2)  DEFAULT 0.0,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_PROJECTS_STATUS CHECK (STATUS IN ('active','completed','paused','cancelled'))
)
GO
COMMENT ON TABLE  PROJECTS              IS '项目管理表'
GO
COMMENT ON COLUMN PROJECTS.ID           IS '主键ID'
GO
COMMENT ON COLUMN PROJECTS.NAME         IS '项目名称'
GO
COMMENT ON COLUMN PROJECTS.DESCRIPTION  IS '项目描述'
GO
COMMENT ON COLUMN PROJECTS.STATUS       IS '项目状态: active活跃/completed已完成/paused暂停/cancelled取消'
GO
COMMENT ON COLUMN PROJECTS.START_DATE   IS '开始日期'
GO
COMMENT ON COLUMN PROJECTS.END_DATE     IS '结束日期'
GO
COMMENT ON COLUMN PROJECTS.PROGRESS     IS '完成进度百分比 0~100'
GO
COMMENT ON COLUMN PROJECTS.CREATED_AT   IS '创建时间'
GO
COMMENT ON COLUMN PROJECTS.UPDATED_AT   IS '更新时间'
GO
CREATE INDEX IDX_PROJECTS_STATUS ON PROJECTS(STATUS)
GO

-- 2.2 TASKS - 任务表
CREATE TABLE TASKS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PROJECT_ID      NUMBER(10),
    TITLE           VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION     CLOB,
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'pending',
    PRIORITY        VARCHAR2(20 CHAR) DEFAULT 'medium',
    DUE_DATE        DATE,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_TASKS_STATUS   CHECK (STATUS   IN ('pending','in_progress','completed','blocked')),
    CONSTRAINT CHK_TASKS_PRIORITY CHECK (PRIORITY IN ('low','medium','high','critical')),
    CONSTRAINT FK_TASKS_PROJECT   FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE SET NULL
)
GO
COMMENT ON TABLE  TASKS              IS '项目任务表'
GO
COMMENT ON COLUMN TASKS.PROJECT_ID   IS '关联项目ID'
GO
COMMENT ON COLUMN TASKS.STATUS       IS '任务状态: pending待处理/in_progress进行中/completed已完成/blocked受阻'
GO
COMMENT ON COLUMN TASKS.PRIORITY     IS '任务优先级: low低/medium中/high高/critical紧急'
GO
CREATE INDEX IDX_TASKS_PROJECT_ID ON TASKS(PROJECT_ID)
GO
CREATE INDEX IDX_TASKS_STATUS     ON TASKS(STATUS)
GO

-- 2.3 EQUIPMENT_TYPES - 机台类型视图 (从 EQUIPMENTINFO 去重 EQUIPMENTTYPE 列)
--     后端 EquipmentType ORM 读取此视图，前端筛选下拉框自动同步量产真实类型
CREATE OR REPLACE VIEW EQUIPMENT_TYPES AS
SELECT
    ROWNUM                                    AS ID,
    EQUIPMENTTYPE                             AS NAME,
    '量产机台类型: ' || EQUIPMENTTYPE          AS DESCRIPTION,
    NULL                                      AS MANUFACTURER
  FROM (
    SELECT DISTINCT EQUIPMENTTYPE
      FROM EQUIPMENTINFO
     WHERE EQUIPMENTTYPE IS NOT NULL
     ORDER BY EQUIPMENTTYPE
  )
GO
COMMENT ON TABLE EQUIPMENT_TYPES IS '机台类型视图 (从 EQUIPMENTINFO 去重 EQUIPMENTTYPE)'
GO

-- 2.4 CONFIGURATIONS - 机台配置项表 (外键引用 EQUIPMENTINFO.EQUIPMENT)
CREATE TABLE CONFIGURATIONS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    EQUIPMENT_NAME  VARCHAR2(32 CHAR),
    CONFIG_KEY      VARCHAR2(100 CHAR) NOT NULL,
    CONFIG_VALUE    CLOB,
    VERSION         VARCHAR2(20 CHAR),
    APPLIED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CONFIG_EQUIPMENT FOREIGN KEY (EQUIPMENT_NAME) REFERENCES EQUIPMENTINFO(EQUIPMENT) ON DELETE CASCADE
)
GO
COMMENT ON TABLE  CONFIGURATIONS             IS '机台配置项历史表 (外键指向量产表 EQUIPMENTINFO)'
GO
COMMENT ON COLUMN CONFIGURATIONS.EQUIPMENT_NAME IS '机台编号 (= EQUIPMENTINFO.EQUIPMENT)'
GO
COMMENT ON COLUMN CONFIGURATIONS.CONFIG_KEY  IS '配置项键名'
GO
COMMENT ON COLUMN CONFIGURATIONS.VERSION     IS '配置版本号'
GO
CREATE INDEX IDX_CONFIG_EQUIPMENT_NAME ON CONFIGURATIONS(EQUIPMENT_NAME)
GO
CREATE INDEX IDX_CONFIG_KEY            ON CONFIGURATIONS(CONFIG_KEY)
GO

-- 2.5 REQUIREMENTS - 需求表 (外键引用 EQUIPMENTINFO.EQUIPMENT)
CREATE TABLE REQUIREMENTS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    TITLE           VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION     CLOB,
    PRIORITY        VARCHAR2(20 CHAR) DEFAULT 'medium',
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'pending',
    PROJECT_ID      NUMBER(10),
    EQUIPMENT_NAME  VARCHAR2(32 CHAR),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_REQ_PRIORITY CHECK (PRIORITY IN ('low','medium','high','critical')),
    CONSTRAINT CHK_REQ_STATUS   CHECK (STATUS   IN ('pending','in_progress','testing','completed','rejected')),
    CONSTRAINT FK_REQ_PROJECT   FOREIGN KEY (PROJECT_ID)     REFERENCES PROJECTS(ID)        ON DELETE SET NULL,
    CONSTRAINT FK_REQ_EQUIPMENT FOREIGN KEY (EQUIPMENT_NAME) REFERENCES EQUIPMENTINFO(EQUIPMENT) ON DELETE SET NULL
)
GO
COMMENT ON TABLE  REQUIREMENTS               IS '需求管理表'
GO
COMMENT ON COLUMN REQUIREMENTS.PRIORITY      IS '需求优先级: low低/medium中/high高/critical紧急'
GO
COMMENT ON COLUMN REQUIREMENTS.STATUS        IS '需求状态: pending待处理/in_progress进行中/testing测试中/completed已完成/rejected已拒绝'
GO
COMMENT ON COLUMN REQUIREMENTS.EQUIPMENT_NAME IS '机台编号 (= EQUIPMENTINFO.EQUIPMENT)'
GO
CREATE INDEX IDX_REQ_PROJECT_ID     ON REQUIREMENTS(PROJECT_ID)
GO
CREATE INDEX IDX_REQ_EQUIPMENT_NAME ON REQUIREMENTS(EQUIPMENT_NAME)
GO
CREATE INDEX IDX_REQ_STATUS         ON REQUIREMENTS(STATUS)
GO
CREATE INDEX IDX_REQ_PRIORITY        ON REQUIREMENTS(PRIORITY)
GO

-- 2.6 CHANGE_RECORDS - 需求变更记录表
CREATE TABLE CHANGE_RECORDS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    REQUIREMENT_ID  NUMBER(10)    NOT NULL,
    CHANGE_TYPE     VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPTION     CLOB,
    FILE_PATH       VARCHAR2(500 CHAR),
    APPLIED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CHANGE_REQ FOREIGN KEY (REQUIREMENT_ID) REFERENCES REQUIREMENTS(ID) ON DELETE CASCADE
)
GO
COMMENT ON TABLE  CHANGE_RECORDS              IS '需求变更记录/修改历史'
GO
COMMENT ON COLUMN CHANGE_RECORDS.CHANGE_TYPE  IS '变更类型，如 modify/delete/add'
GO
COMMENT ON COLUMN CHANGE_RECORDS.FILE_PATH    IS '关联代码/配置文件路径'
GO
CREATE INDEX IDX_CHANGE_REQ_ID ON CHANGE_RECORDS(REQUIREMENT_ID)
GO

-- 2.7 REPORTS - 报表表
CREATE TABLE REPORTS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    TITLE           VARCHAR2(200 CHAR) NOT NULL,
    REPORT_DATE     DATE            NOT NULL,
    CONTENT         CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
)
GO
COMMENT ON TABLE  REPORTS             IS '报表/周报/月报存储'
GO
COMMENT ON COLUMN REPORTS.REPORT_DATE IS '报表所属日期'
GO
CREATE INDEX IDX_REPORTS_DATE ON REPORTS(REPORT_DATE)
GO

-- 2.8 NOTES_DOCUMENTS - HCL Notes 文档同步表
CREATE TABLE NOTES_DOCUMENTS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NOTES_ID        VARCHAR2(100 CHAR),
    TITLE           VARCHAR2(200 CHAR),
    CONTENT         CLOB,
    URL             VARCHAR2(500 CHAR),
    PROJECT_ID      NUMBER(10),
    SYNC_AT         TIMESTAMP,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_NOTES_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE SET NULL
)
GO
COMMENT ON TABLE  NOTES_DOCUMENTS          IS 'HCL Notes 文档同步缓存表'
GO
COMMENT ON COLUMN NOTES_DOCUMENTS.NOTES_ID IS 'Notes 文档唯一UNID'
GO
COMMENT ON COLUMN NOTES_DOCUMENTS.SYNC_AT  IS '最后一次同步时间'
GO
CREATE INDEX IDX_NOTES_PROJECT_ID ON NOTES_DOCUMENTS(PROJECT_ID)
GO

-- 2.9 USERS - 用户表
CREATE TABLE USERS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    USERNAME        VARCHAR2(100 CHAR) NOT NULL,
    DISPLAY_NAME    VARCHAR2(200 CHAR),
    EMAIL           VARCHAR2(200 CHAR),
    ROLE            VARCHAR2(50 CHAR) DEFAULT 'user',
    DEPARTMENT      VARCHAR2(100 CHAR),
    TEAM            VARCHAR2(100 CHAR),
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'active',
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
)
GO
COMMENT ON TABLE  USERS              IS '系统用户表'
GO
COMMENT ON COLUMN USERS.USERNAME     IS '登录账号(唯一)'
GO
COMMENT ON COLUMN USERS.DISPLAY_NAME IS '显示名称'
GO
COMMENT ON COLUMN USERS.ROLE         IS '角色: admin/engineer/user'
GO
COMMENT ON COLUMN USERS.STATUS       IS '账号状态: active启用/inactive禁用'
GO
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME)
GO

-- 2.10 SYSTEM_SETTINGS - 系统设置表
CREATE TABLE SYSTEM_SETTINGS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    KEY             VARCHAR2(100 CHAR) NOT NULL,
    VALUE           CLOB,
    DESCRIPTION     VARCHAR2(500 CHAR),
    CATEGORY        VARCHAR2(50 CHAR) DEFAULT 'general',
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT UK_SYS_SETTINGS_KEY UNIQUE (KEY)
)
GO
COMMENT ON TABLE  SYSTEM_SETTINGS          IS '系统参数/配置存储表'
GO
COMMENT ON COLUMN SYSTEM_SETTINGS.KEY      IS '配置键名(唯一)'
GO
COMMENT ON COLUMN SYSTEM_SETTINGS.CATEGORY IS '配置分类: general/ai/notes/equipment'
GO
CREATE INDEX IDX_SYS_SETTINGS_KEY      ON SYSTEM_SETTINGS(KEY)
GO
CREATE INDEX IDX_SYS_SETTINGS_CATEGORY ON SYSTEM_SETTINGS(CATEGORY)
GO

-- 2.11 WORK_CATEGORIES - 工作类别表
CREATE TABLE WORK_CATEGORIES (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME            VARCHAR2(100 CHAR) NOT NULL,
    CODE            VARCHAR2(50 CHAR)  NOT NULL,
    DESCRIPTION     VARCHAR2(500 CHAR),
    ICON            VARCHAR2(50 CHAR),
    COLOR           VARCHAR2(20 CHAR),
    SORT_ORDER      NUMBER(10)    DEFAULT 0,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_WORK_CATEGORIES_CODE UNIQUE (CODE)
)
GO
COMMENT ON TABLE  WORK_CATEGORIES            IS '工作管理-工作类别字典'
GO
COMMENT ON COLUMN WORK_CATEGORIES.CODE       IS '类别代码(唯一，英文标识)'
GO
COMMENT ON COLUMN WORK_CATEGORIES.SORT_ORDER IS '显示排序序号'
GO
COMMENT ON COLUMN WORK_CATEGORIES.COLOR      IS '前端标签颜色(HEX)'
GO
CREATE INDEX IDX_WORK_CATEGORIES_CODE ON WORK_CATEGORIES(CODE)
GO

-- 2.12 WORK_ITEMS - 工作项表
CREATE TABLE WORK_ITEMS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CATEGORY_ID     NUMBER(10),
    TITLE           VARCHAR2(500 CHAR) NOT NULL,
    DETAILS         CLOB,
    URGENCY         VARCHAR2(20 CHAR) DEFAULT 'na',
    IMPORTANCE      VARCHAR2(20 CHAR) DEFAULT 'na',
    STATUS          VARCHAR2(30 CHAR) DEFAULT 'pending',
    PRIORITY_SCORE  NUMBER(20,10)  DEFAULT 0.0,
    DUE_DATE        DATE,
    PROJECT_ID      NUMBER(10),
    SOURCE_TYPE     VARCHAR2(50 CHAR) DEFAULT 'manual',
    SOURCE_URL      VARCHAR2(1000 CHAR),
    AI_NOTES        CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_WORKITEM_URGENCY    CHECK (URGENCY    IN ('na','low','medium','high')),
    CONSTRAINT CHK_WORKITEM_IMPORTANCE CHECK (IMPORTANCE IN ('na','low','medium','high')),
    CONSTRAINT FK_WORKITEM_CATEGORY    FOREIGN KEY (CATEGORY_ID) REFERENCES WORK_CATEGORIES(ID) ON DELETE SET NULL,
    CONSTRAINT FK_WORKITEM_PROJECT     FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(ID)        ON DELETE SET NULL
)
GO
COMMENT ON TABLE  WORK_ITEMS                  IS '工作管理-工作项(待办事项)'
GO
COMMENT ON COLUMN WORK_ITEMS.URGENCY          IS '紧急度: na不适用/low低/medium中/high高'
GO
COMMENT ON COLUMN WORK_ITEMS.IMPORTANCE       IS '重要性: na不适用/low低/medium中/high高'
GO
COMMENT ON COLUMN WORK_ITEMS.STATUS           IS '状态: pending待处理/in_progress进行中/completed已完成/blocked受阻'
GO
COMMENT ON COLUMN WORK_ITEMS.PRIORITY_SCORE   IS 'AI计算的优先级分数'
GO
COMMENT ON COLUMN WORK_ITEMS.SOURCE_TYPE      IS '来源类型: manual手动/table_import导入/notes同步'
GO
CREATE INDEX IDX_WORKITEM_CATEGORY_ID ON WORK_ITEMS(CATEGORY_ID)
GO
CREATE INDEX IDX_WORKITEM_PROJECT_ID  ON WORK_ITEMS(PROJECT_ID)
GO
CREATE INDEX IDX_WORKITEM_STATUS      ON WORK_ITEMS(STATUS)
GO
CREATE INDEX IDX_WORKITEM_PRIORITY    ON WORK_ITEMS(PRIORITY_SCORE)
GO

-- 2.13 DAILY_PLANS - 每日计划表
CREATE TABLE DAILY_PLANS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PLAN_DATE       DATE            NOT NULL,
    USER_ID         NUMBER(10),
    ITEMS_ORDER     CLOB,
    AI_SUGGESTIONS  CLOB,
    SUMMARY         CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_DAILYPLAN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
)
GO
COMMENT ON TABLE  DAILY_PLANS              IS '工作管理-每日工作计划'
GO
COMMENT ON COLUMN DAILY_PLANS.PLAN_DATE    IS '计划日期(唯一组合)'
GO
COMMENT ON COLUMN DAILY_PLANS.ITEMS_ORDER  IS '排序后的工作项ID序列(JSON)'
GO
CREATE UNIQUE INDEX IDX_DAILYPLAN_DATE_USER ON DAILY_PLANS(PLAN_DATE, USER_ID)
GO

-- 2.14 WORK_LOGS - 工作项变更日志表
CREATE TABLE WORK_LOGS (
    ID              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    WORK_ITEM_ID    NUMBER(10),
    ACTION          VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPTION     CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_WORKLOG_ITEM FOREIGN KEY (WORK_ITEM_ID) REFERENCES WORK_ITEMS(ID) ON DELETE CASCADE
)
GO
COMMENT ON TABLE  WORK_LOGS           IS '工作管理-工作项操作变更日志'
GO
COMMENT ON COLUMN WORK_LOGS.ACTION    IS '操作动作: create/update/delete/status_change'
GO
CREATE INDEX IDX_WORKLOG_ITEM_ID   ON WORK_LOGS(WORK_ITEM_ID)
GO
CREATE INDEX IDX_WORKLOG_CREATED   ON WORK_LOGS(CREATED_AT)
GO

-- ----------------------------------------------------------------------------
-- 3. INSERT INIT DATA - 初始化基础数据
-- ----------------------------------------------------------------------------
-- ⚠️ 不插入任何机台数据: EQUIPMENTINFO 已是生产真实数据，直接展示即可。
--    以下只插入业务基础数据 (项目/任务/需求/用户/系统设置/工作类别)。

-- 3.1 项目 PROJECTS (5个 — 业务种子数据)
INSERT INTO PROJECTS (NAME, DESCRIPTION, PROGRESS) VALUES ('机台驱动升级项目', '升级所有机台的驱动版本',        65.0)
GO
INSERT INTO PROJECTS (NAME, DESCRIPTION, PROGRESS) VALUES ('CIM系统优化',     '优化CIM系统性能',               40.0)
GO
INSERT INTO PROJECTS (NAME, DESCRIPTION, PROGRESS) VALUES ('新项目设备接入',  '新项目设备接入CIM系统',         25.0)
GO
INSERT INTO PROJECTS (NAME, DESCRIPTION, PROGRESS) VALUES ('自动化测试框架',  '建立自动化测试框架',             80.0)
GO
INSERT INTO PROJECTS (NAME, DESCRIPTION, PROGRESS) VALUES ('数据采集系统',    '升级数据采集系统',               50.0)
GO

-- 3.2 任务 TASKS (8条 — 业务种子数据)
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (1, '光刻机驱动开发',     'high')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (1, '刻蚀机驱动测试',     'medium')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (2, '数据库性能调优',     'high')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (2, 'API接口优化',        'medium')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (3, '新设备调研',         'medium')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (4, '测试用例编写',       'medium')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (4, '测试框架部署',       'high')
GO
INSERT INTO TASKS (PROJECT_ID, TITLE, PRIORITY) VALUES (5, '数据采集脚本开发',   'high')
GO

-- 3.3 需求 REQUIREMENTS (5条 — 业务种子数据)
--     示例: 关联到 EQUIPMENTINFO.EQUIPMENT 中真实存在的机台编号 (执行人按实际修改)
INSERT INTO REQUIREMENTS (TITLE, DESCRIPTION, PRIORITY, PROJECT_ID) VALUES ('机台A驱动升级',   '将机台A的驱动从v1升级到v2',       'high',     1)
GO
INSERT INTO REQUIREMENTS (TITLE, DESCRIPTION, PRIORITY, PROJECT_ID) VALUES ('新增机台配置项',   '为机台新增配置项支持',             'medium',   1)
GO
INSERT INTO REQUIREMENTS (TITLE, DESCRIPTION, PRIORITY, PROJECT_ID) VALUES ('机台B上线',       '新机台B上线部署',                 'critical', 3)
GO
INSERT INTO REQUIREMENTS (TITLE, DESCRIPTION, PRIORITY, PROJECT_ID) VALUES ('报表功能优化',    '优化现有报表功能',                 'low',      2)
GO
INSERT INTO REQUIREMENTS (TITLE, DESCRIPTION, PRIORITY, PROJECT_ID) VALUES ('系统告警优化',    '优化系统告警机制',                 'medium',   2)
GO

-- 3.4 用户 USERS (3个默认用户)
INSERT INTO USERS (USERNAME, DISPLAY_NAME, EMAIL, ROLE, DEPARTMENT, TEAM) VALUES ('administrator', '管理员',   'admin@company.com', 'admin',      'IT',   'CIM')
GO
INSERT INTO USERS (USERNAME, DISPLAY_NAME, EMAIL, ROLE, DEPARTMENT, TEAM) VALUES ('eap.engineer',  'EAP工程师', 'eap@company.com',   'engineer',   '制造', 'EAP')
GO
INSERT INTO USERS (USERNAME, DISPLAY_NAME, EMAIL, ROLE, DEPARTMENT, TEAM) VALUES ('cim.user',      'CIM用户',  'cim@company.com',   'user',       '制造', 'CIM')
GO

-- 3.5 系统设置 SYSTEM_SETTINGS (general/ai/notes/equipment 9项默认值)
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('system_name',       'CIM Work Manager',                 '系统名称',                  'general')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('openai_api_key',    '',                                  'OpenAI API Key',            'ai')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('openai_api_base',   'https://api.openai.com/v1',         'OpenAI API Base URL',       'ai')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('ai_model',          'gpt-4o-mini',                       'AI Model Name',             'ai')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('notes_server_url',  '',                                  'HCL Notes Server URL',      'notes')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('notes_user',        '',                                  'HCL Notes Username',        'notes')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('notes_password',    '',                                  'HCL Notes Password',        'notes')
GO
-- Git Source 配置 (前端 🐙 按钮跳转用)
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('git_source_base_url', 'https://github.com/leanerone/web/blob/main/equipment', 'Git 源码基础 URL', 'equipment')
GO
INSERT INTO SYSTEM_SETTINGS (KEY, VALUE, DESCRIPTION, CATEGORY) VALUES ('git_source_map', '{"1":"cpc/asm_eagle","2":"pecvd/asm_trident","3":"gateox/tel_8280","4":"tteox/thermawave_op5205t","5":"cateox/asml_8350"}', 'SOURCECODE→Git子路径映射(JSON)', 'equipment')
GO

-- 3.6 工作类别 WORK_CATEGORIES (8个字典)
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('Operation/Follow up', 'operation',    '日常操作跟进',     '🔄', '#3B82F6', 1)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('Requirement',         'requirement',  '需求跟进与管理',   '📋', '#8B5CF6', 2)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('SIT',                 'sit',          '系统集成测试',     '🔬', '#06B6D4', 3)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('Place then GO',       'place_then_go','上线部署跟踪',     '🚀', '#10B981', 4)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('AI开发',              'ai_dev',       'AI项目开发与部署', '🤖', '#F59E0B', 5)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('RCMS',                'rcms',         'RCMS系统测试',     '🔧', '#EF4444', 6)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('Other',               'other',        '其他工作',         '📦', '#6B7280', 7)
GO
INSERT INTO WORK_CATEGORIES (NAME, CODE, DESCRIPTION, ICON, COLOR, SORT_ORDER) VALUES ('System HandOver',     'handover',     '系统交接',         '🔗', '#EC4899', 8)
GO

-- ----------------------------------------------------------------------------
-- 4. init_oracle.sql 执行结果自检
-- ----------------------------------------------------------------------------
SELECT 'PROJECTS'         AS TBL, COUNT(*) AS CNT FROM PROJECTS         UNION ALL
SELECT 'TASKS',             COUNT(*) FROM TASKS              UNION ALL
SELECT 'EQUIPMENT_TYPES',   COUNT(*) FROM EQUIPMENT_TYPES    UNION ALL
SELECT 'EQUIPMENTINFO',     COUNT(*) FROM EQUIPMENTINFO      UNION ALL
SELECT 'CONFIGURATIONS',    COUNT(*) FROM CONFIGURATIONS     UNION ALL
SELECT 'REQUIREMENTS',      COUNT(*) FROM REQUIREMENTS       UNION ALL
SELECT 'CHANGE_RECORDS',    COUNT(*) FROM CHANGE_RECORDS     UNION ALL
SELECT 'REPORTS',           COUNT(*) FROM REPORTS            UNION ALL
SELECT 'NOTES_DOCUMENTS',   COUNT(*) FROM NOTES_DOCUMENTS    UNION ALL
SELECT 'USERS',             COUNT(*) FROM USERS              UNION ALL
SELECT 'SYSTEM_SETTINGS',   COUNT(*) FROM SYSTEM_SETTINGS    UNION ALL
SELECT 'WORK_CATEGORIES',   COUNT(*) FROM WORK_CATEGORIES    UNION ALL
SELECT 'WORK_ITEMS',        COUNT(*) FROM WORK_ITEMS         UNION ALL
SELECT 'DAILY_PLANS',       COUNT(*) FROM DAILY_PLANS        UNION ALL
SELECT 'WORK_LOGS',         COUNT(*) FROM WORK_LOGS
ORDER BY 1
GO

PRINT '==============================================================='
PRINT ' init_oracle.sql 执行完成!                                     '
PRINT ' 已创建 13 张业务表 + 1 个类型视图 (EQUIPMENT_TYPES 视图)     '
PRINT ' 业务基础数据: PROJECTS=5, TASKS=8, REQUIREMENTS=5, USERS=3,   '
PRINT '               SYS_SET=9(含 git_source_* 2条), CAT=8          '
PRINT '                                                               '
PRINT ' ✅ EQUIPMENTINFO = 量产真实机台数据 (未受影响, 直接读取展示) '
PRINT ' ✅ EQUIPMENT_TYPES 视图 = 从 EQUIPMENTINFO 去重类型          '
PRINT '                                                               '
PRINT ' 单步部署完成! 直接启动后端即可使用。                          '
PRINT '==============================================================='
GO
